<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'View' => 'Просмотр',
    'Field {fileinput} is empty or path {path} can\'t be created.' => 
        'Поле ввода {fileinput} пусто или каталог {path} не может юыть создан.',
    'File can\'t be uploaded.' => 'Файл не может быть загружен',
    'File size {size} is too small or big. Min {min}, max {max} bytes allowed.' => 
        'Размер файла {size} слишком велик или мал. Min {min}, max {max} байт возможно.',
    'File type {type} is not allowed.' => 'Тип файла {type} не разрешен.',
    'Information about file {name} can\'t be saved in a model.' => 'Информация о файле {name} не может быть сохранена.',
    'Temporary file can\'t be moved to file {name}.' => 'Временный файл не может быть перемещен в файл {name}.',
    'The width or height of the image, or both, is smaller than necessary [{width}, {height}]px.' =>
        'Ширина или высота изображения меньше возможного минимума [{width}, {height}]px.',
    'Too many files uploaded. Allowed {max}.' => 'Слишком много файлов уже загружено. Допустимо {max}.',
    'After saving you will be able to upload images or other files.' => 'После сохранения вы сможете загружать изображения или другие файлы.',
    'Are you shure you want to delete this element?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Cancel' => 'Отменить',
    'Choose a file' => 'Выберите файл',
    'Crop' => 'Обрезать',
    'File size can be from {minFileSize} to {maxFileSize}Mb' => 'Размер файла может быть от {minFileSize} до {maxFileSize}Mb',
    'Only {maxFiles} file(s) can be uploaded.' => 'Только {maxFiles} файл(а|ов) может быть загружено.',
    'Photo' => 'Фото',
    'Rows can be sorted - click, hold, drag.' => 'Строки можно сортировать - кликните, держите, тащите.',
    'Sort' => 'Сортировка',
    'There is not right file type! Allowed type(s) - {acceptFileTypes}.' => 'Не верный тип файла! Разрешенные тип(ы) - {acceptFileTypes}.',
    'Upload' => 'Загрузить',
    'cancel' => 'отменить',
    'delete' => 'удалить',
    'edit' => 'изменить',
    'save' => 'сохранить',
];
