<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'After saving you will be able to upload images' => 'После сохранения вы сможете загружать изображения',
    'Are you shure you want to delete this element?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Choose a file' => 'Выберите файл',
    'File size can be from {minFileSize} to {maxFileSize}Mb' => 'Размер файла может быть от {minFileSize} до {maxFileSize}Mb',
    'Only {maxFiles} file(s) can be uploaded.' => 'Только {maxFiles} файл(а|ов) может быть загружено.',
    'Photo' => 'Фото',
    'Rows can be sorted - click, hold, drag.' => 'Строки можно сортировать - кликните, держите, тащите.',
    'Sort' => 'Сортировка',
    'There is not right file type! Allowed type(s) - {acceptFileTypes}.' => 'Не верный тип файла! Разрешенные тип(ы) - {acceptFileTypes}.',
    'Upload' => 'Загрузить',
    'cancel' => 'отменить',
    'delete' => 'удалить',
    'edit' => 'изменить',
    'save' => 'сохранить',
];
